### ISSUE TITLE
不好意思，冒昧的打扰一下，关于美团逆向的

### ISSUE THREAD

**Issue by anjia0532** [xqin/mirror#1]
不好意思，实在联系不上您本人，所以咨询了陈琦大佬 [Tech：美团iOS逆向工程分析](https://chenqi.app/Meituan-iOS-Reverse-Engineering/) 后，他推荐了您。想有偿咨询一下美团逆向的问题

方便的话，可以email沟通下么？[anjia0532@gmail.com](mailto:anjia0532@gmail.com?subject=[GitHub]%E7%BE%8E%E5%9B%A2%E9%80%86%E5%90%91)

**Comment by xqin** [comment]
不好意思, 不对外提供任何技术支持.

**Comment by anjia0532** [comment]
嗯，好的，理解，谢谢
